### ISSUE TITLE
Provide prebuild postgres and elastics containers (dockerhub)

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/annotatedb#32]
For simple integration with other projects prebuild containers containing all the data should be provided. This will allow users to integrate annotatedb with existing project as simple as stating the image in the docker-compose file
```
  adb_postgres:
    image: annotatedb/adb_postgres:0.1.1
    ports:
      - "5434:5432"
  adb_elasticsearch:
    image: annotatedb/adb_elasticsearch:0.1.1
    ports:
      - "9124:9200"
```
